name: 'Discord changelog action'
description: 'Extracts the changelog from the text and sends it to Discord'
inputs:
  webhook_url:
    required: true
  pull_request_url:
    required: true
  github_token:
    required: false
    default: ${{ github.token }}
  webhook_username:
    required: false
  webhook_avatar_url:
    required: false
  changelog_replace_data:
    required: false
runs:
  using: 'node20'
  main: 'dist/action/index.js'